language: ruby


jobs:
  include:
    - stage: not pr
      script:
        - echo "$test"
        - echo "asdf nahradit asdjklhas kldajsdkj adjls as" > file.txt
        - echo "$test2"
        - sed -i "s/nahradit/$test2/g" file.txt
        - cat file.txt
        - echo "nene"
      if: NOT type = "pull_request"
    - stage: all
      script:
        - echo "$test"
        - echo "asdf nahradit asdjklhas kldajsdkj adjls as" > file.txt
        - echo "$test2"
        - sed -i "s/nahradit/$test2/g" file.txt
        - cat file.txt
        - echo "nene"

